default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
        stages: [commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        stages:  [commit, push]
        args: ["--select", "B018"]
      # - id: ruff-format
      #   stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        stages: [commit]
      # additional_dependencies: ["click==7.1.2"]

  - repo: local
    hooks:
      - id: django-check
        name: Django check
        language: system
        entry: bash
        args: [-c, 'source ./.envrc; python manage.py makemigrations --dry-run --check']
        pass_filenames: false
        stages: [push]

      - id: django-migrate-check
        name: Django migrate check
        language: system
        entry: bash
        args: [-c, 'source ./.envrc; python manage.py migrate --check']
        pass_filenames: false
        stages: [push]

      - id: django-queryset-noop
        name: Detect ignored QuerySet calls (filter/exclude/annotate/...)
        language: system
        entry: scripts/check_unused_queryset_calls.py
        files: \.py$
        stages: [commit, push]